### ISSUE TITLE
Model versions not exported for missing runs

### ISSUE THREAD

**Issue by hashemraslan** [amesar/mlflow-export-import#38]
https://github.com/amesar/mlflow-export-import/blob/def02556a46f18013ef434f78671d8625b1ef13a/mlflow_export_import/model/export_model.py#L50

When run information is not available, the version details is not exported

**Comment by amesar** [comment]
The public MLflow API requires a run ID parameter in order to create a model version in the target tracking server (Databricks workspace). See [MlflowClient.create_model_version](https://www.mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.create_model_version). 
Example in the tool: [import_model.py#L24](https://github.com/amesar/mlflow-export-import/blob/master/mlflow_export_import/model/import_model.py#L24)

**Comment by amesar** [comment]
Which script are you using? model/export_model.py or bulk/export_models.py?

**Comment by amesar** [comment]
Use this tool to show you which registered model version don't have a valid backing run.
https://github.com/amesar/mlflow-tools/tree/master/mlflow_tools/tools#list-all-model-versions-and-their-backing-run
